- name: "server test cd"
  hosts: docker
  tasks:
    - name: "Signin Dockerhub"
      docker_login:
        username: virtus
        password: bes@83HUB

    - name: "Stop existing container"
      docker_compose:
        project_src: "/home/ubuntu/projetapi/grp4/"
        state: absent
      ignore_errors: yes

    - name: "Remove local image"
      docker_image:
        state: absent
        name: "virtus/david:projetapi"

    - name: "Pull Dockerhub images"
      docker_image:
        name: "virtus/david:projetapi"
        source: pull

    - name: "Copy docker-compose.yml"
      copy:
        src: "ansible/docker-compose.yml"
        dest: "/home/ubuntu/projetapi/grp4/"
        owner: "ubuntu"
        group: "ubuntu"

    - name: "Up Container"
      docker_compose:
        project_src: "/home/ubuntu/projetapi/grp4/"
        state: present
        pull: yes
        recreate: always
